# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo foo > $(Build.SourcesDirectory)/foo
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- publish: $(Build.SourcesDirectory)/foo
  artifact: o3de
  displayName: Publish profile build